name: RunScraperApartments_m2
run-name: ScrapeApartments_m2
on: 
  schedule:
    #    - cron: '*/10 * * * *' 
    - cron: '7 9 * * *' 
  workflow_dispatch:
    inputs:
      job_to_run:
        description: 'Which job to run?'
        required: true
        type: choice
        options:
          - ScrapeApartments_m2_medellin
          - ScrapeApartments_m2_la-estrella
jobs:
  ScrapeApartments_m2_medellin:
    if: (github.event_name == 'workflow_dispatch' && github.event.inputs.job_to_run == 'ScrapeApartments_m2_medellin') || github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install ubuntu packages
        run:  sudo apt-get  install -y google-chrome-stable python3-lxml
      
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: execute py script # run main.py
        run: |
          ls
          pwd
          python src/ScrapingApartments_m2.py medellin
          ls
          pwd

      - name: update csv file
        run: |
          pwd
          git config --global user.email "AldeaAI@protonmail.comm"
          git config --global user.name "AldeaAI"
          git add -A 
          git commit -m 'Created csv file for the apartments'
          git push

  ScrapeApartments_m2_la-estrella:
    if: (github.event_name == 'workflow_dispatch' && github.event.inputs.job_to_run == 'ScrapeApartments_m2_la-estrella') || github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install ubuntu packages
        run:  sudo apt-get  install -y google-chrome-stable python3-lxml

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: execute py script # run main.py
        run: |
          ls
          pwd
          python src/ScrapingApartments_m2.py la-estrella
          ls
          pwd

      - name: update csv file
        run: |
          pwd
          git config --global user.email "AldeaAI@protonmail.comm"
          git config --global user.name "AldeaAI"
          git add -A
          git commit -m 'Created csv file for the apartments'
          git push

       
